version: "3.9"

services:
  quarto:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISPLAY:
    image: quarto:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
  quarto-pre:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-pre
    environment:
      DISPLAY:
    image: quarto-pre:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash