version: "3.9"

x-default: &default
  init: true
  environment:
    DISPLAY:
  volumes:
    # passing through this file allows opening windows from the container in your host computer
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/data:/data"
    - "$PWD:/opt/project"
  network_mode: "host"
  command:
    - /bin/bash  

services:
  quarto-18:
    <<: *default
    image: quarto-18:develop
    build:
      context: .
      dockerfile: Dockerfile-18

  quarto-17:
    <<: *default
    image: quarto-17:develop
    build:
      context: .
      dockerfile: Dockerfile-17
  
  quarto-16:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile-16
    image: quarto-16:develop
 
  quarto-15:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-15
    environment:
      DISPLAY:
    image: quarto-15:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
  quarto-14:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-14
    environment:
      DISPLAY:
    image: quarto-14:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
  quarto-13:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-13
    environment:
      DISPLAY:
    image: quarto-13:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
  quarto-12:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-12
    environment:
      DISPLAY:
    image: quarto-12:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    command:
      - /bin/bash
